<?php
$component = new ComponentRenderer();
?>
<h3>Forms</h3>
<?= $component->formTextElement('Name', 'name', 'name') ?>
<?= $component->formTextElement('Email', 'email', 'email') ?>

<h3>Alerts</h3>
<?= $component->alert('Default alert', 'default') ?>
<?= $component->alert('Warning alert', 'warning',true, 'This is a description') ?>
<?= $component->alert('Info alert', 'info') ?>
<?= $component->alert('Error alert', 'error') ?>
<?= $component->alert('Success alert', 'success') ?>

<h3>Buttons</h3>
<?= $component->button('button','Button', 'default') ?>
<?= $component->button('button','Button', 'primary') ?>
<?= $component->button('button','Button', 'warning') ?>
<?= $component->button('button','Button', 'danger') ?>
<?= $component->button('button','Button', 'success') ?>