<?php
$component = new ComponentRenderer();
?>
<?php $hero_other = $component->button('a', 'Learn More', 'primary', null, ['href'=>'/about']) ?>
<?= $component->hero('/lib/hero-medium.jpg', 'Newton Framework', 'Mobile-first, Lightweight, Responsive', $hero_other) ?>
<section class="trapezoid">
	<div class="fitty fitty-icon"><i class="fa fa-mobile" aria-hidden="true" aria-label="Mobile Phone"></i></div>
	<div class="fitty align-left">
		Designed for mobile, <br><br>
		<span class="spacer"></span> adapted for desktop
	</div>
</section>

<section class="trapezoid">
	<div class="fitty align-right">
		1.1 MB download, <span class="spacer"></span><span class="spacer"></span><br><br>
		Speedy loading even on 2G
	</div>
	<div class="fitty fitty-icon"><i class="fa fa-cloud" aria-hidden="true" aria-label="Cloud"></i></div>
</section>

<section class="trapezoid">
	<div class="fitty fitty-icon"><i class="fa fa-arrows" aria-hidden="true" aria-label="multi-directional arrow cross"></i></div>
	<div class="fitty align-left">
		Eases into any width,<br><br>
		<span class="spacer"></span> consistently smooth user experience
	</div>
</section>

<section class="trapezoid">
	<div class="fitty align-right">
		Swapping over is a breeze,<span class="spacer"></span><span class="spacer"></span><br><br>
		squeaky clean and customizable
	</div>
	<div class="fitty fitty-icon"><i class="fa fa-code" aria-hidden="true" aria-label="code braces"></i></div>
</section>

<section class="trapezoid">
	<div class="fitty fitty-icon"><i class="fa fa-usd" aria-hidden="true" aria-label="dollar sign"></i></div>
	<div class="fitty align-left">
		Absolutely<br><br>
		<span class="spacer"></span>100%<br><br>
		<span class="spacer"></span><span class="spacer"></span>Free
	</div>
</section>