<?php
$component = new ComponentRenderer();
?>
<?php $hero_other = $component->button('a', 'Learn More', 'primary', null, ['href'=>'/about']) ?>
<?= $component->hero('/lib/pexels-photo-39811.jpeg', 'Newton Framework', 'Mobile-first, Lightweight, Responsive', $hero_other) ?>
<section class="trapezoid">
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi velit tortor, volutpat vitae ex id,
tincidunt sagittis dolor. Nunc consequat odio mi, in pharetra lectus consectetur in. Nunc porttitor
nibh a orci hendrerit, vitae ultricies sem venenatis. Sed tempus libero non laoreet euismod. Morbi
non erat enim. Donec rutrum turpis elit, eu porttitor nisl consectetur id. Duis in hendrerit lectus.
</section>

<section class="trapezoid">
Etiam at molestie mi. In hac habitasse platea dictumst. Vestibulum fermentum bibendum aliquet.
Integer mauris lectus, rutrum vitae metus sed, lobortis imperdiet magna. Aenean iaculis orci ac
interdum ultrices. Morbi eget elit tincidunt, bibendum risus eget, feugiat ex. Ut at porta arcu,
sed malesuada turpis. Ut urna lorem, laoreet vitae euismod ut, porttitor id enim. Ut imperdiet risus
sem, nec gravida augue suscipit eget. Nunc vitae suscipit ligula.
</section>

<section class="trapezoid">
Donec vel porta elit. Maecenas convallis mauris id lectus placerat pellentesque. Nullam rhoncus
nunc magna, ac sollicitudin erat condimentum vel. Phasellus in urna ut libero eleifend fermentum
eget in metus. Ut sodales posuere augue, vel elementum tortor blandit eget. Curabitur in libero
elementum, pellentesque augue vitae, malesuada purus. Quisque luctus orci a magna facilisis laoreet.
Ut vitae arcu feugiat, blandit augue porta, tempus nulla. Maecenas sed vehicula lectus. Nullam malesuada
id nisl in convallis. Aenean posuere consectetur velit, eu mattis ex commodo sed. Fusce vel orci
tincidunt libero porttitor dapibus. Cras gravida urna eros. In hac habitasse platea dictumst.
</section>

<section class="trapezoid">
Morbi vestibulum lectus diam, vestibulum laoreet sem tempor eget. Aenean nec lobortis ipsum, eu tristique turpis.
Sed sed dui eleifend, condimentum justo sit amet, tincidunt erat. Praesent ultrices ultrices ex, eu consectetur
quam suscipit rhoncus. Aenean eget magna enim. Pellentesque ut magna tincidunt, ultrices lacus ut, faucibus neque.
Morbi porttitor quis magna at viverra.
</section>

<section class="trapezoid">
Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
Integer rutrum gravida nibh, eu sodales lorem. Cras fringilla felis sapien, non luctus quam
scelerisque a. Duis vel molestie nisl, a posuere tellus. Fusce non aliquam sapien, vel scelerisque
purus. Nulla venenatis turpis a massa congue hendrerit. Vestibulum nisi lacus, commodo nec justo
sed, finibus vehicula eros. Nullam eget enim a lacus faucibus auctor a eu turpis. Nam lectus sapien,
dictum eu euismod eget, vehicula id tellus. Morbi enim nisi, faucibus non ipsum id, rhoncus tincidunt
magna. Sed sodales, lorem ut dignissim imperdiet, purus augue scelerisque erat, sit amet placerat nulla
tortor eget tellus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
Maecenas quis velit egestas, pulvinar dolor in, rhoncus lectus. Donec vestibulum dui nec eros lobortis, nec
iaculis lacus cursus.
</section>